version: '2.0'
services:
  web:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    - logvolume01:/var/log
    links:
    - mongo
  mongo:
    image: redis
volumes:
  logvolume01: {}