version: '3.0'
services:
    web:
        build: .
        environment:
            FLASK_ENV: production
            #MONGO_URI: 'mongodb://mongo:27017/covid'
            # MONGO_URI: 'mongodb://0.0.0.0:27017/covid'
        ports:
            - "5000:5000"
        depends_on:
            - elasticsearch

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
        ports:
            - "9200:9200"
        volumes:
            - elastic:/usr/share/elasticsearch/data
        tty: true
        environment:
            discovery.type: single-node

    volumes:
        elastic:
            driver: local

